### ISSUE TITLE
ability to select folder to download from

### ISSUE THREAD

**Issue by mixedup4x4** [tarrell13/Nessus-Quick-Scripts#1]
is there a way to select a folder to download the scans from?  I have multiple folders based on the scans I am doing, and would really like a way to "list them" and then select the folder to download from

**Comment by tarrell13** [comment]
I am so sorry, I had no idea this issue was opened up for the project. I can add that feature as I see it can definitely be useful.

**Comment by tarrell13** [comment]
Added the feature and updated README
